# Where Things Are
source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
collections: null

## Setup
title: 'Algomash'
tagline: 'Create Documentation Website Using Jekyll'
description: 'Algomash is a Jekyll boilerplate with necessary operations for creating Documentation website for small projects.'
baseurl:
#assets: http://algomash.com/assets/

#Collections for Documentation
collections:
  docs:
   output: true
   permalink: /docs/:path


# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: /:categories/:title/
paginate_path: /page:num
paginate: 15
timezone: America/Chicago
include: ['_pages']
relative_permalinks: false
quiet:    false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
